root = "gemini.circumlunar.space" #Root Seed
timeout = 5                       #Connection Timeout(in secs)
database = "store.db"             #Sqlite file

[cache] #Bloom Filter config
expected_web_pages = 100000
false_positive_rate = 0.01
